spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        enabled: true
        lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer: http://${KEYCLOAK_SERVER}:${KEYCLOAK_PORT}/realms/mscorsorealm


server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://cursoms-eureka-user:M1c9j812@${EUREKA_SERVER}:8761/eureka
