spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        enabled: true
        lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer: http://localhost:8081/realms/mscorsorealm


server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://cursoms-eureka-user:M1c9j812@localhost:8761/eureka
